name: use input parameters
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose an environment to deploy the application to
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: choose a git tag to deploy
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app on provided environment
        run: echo "deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
