name: or evaluation
on: push
jobs:
  run-for-demo:
    runs-on: ubuntu-latest
    steps:
      - name: get actor
        id: step1
        run: echo "actor=${{ github.actor }}" >> GITHUB.OUTPUT

      - name: print actor
        run: echo "The actor is ${{ steps.step1.outputs.actor }}"

      - name: run for actor or Zinhle
        if: github.actor=='steps.step1.outputs.actor' || github.actor=='Zinhle'
        run: echo "ran for Karabo or zinhle"