name: reusable workflow
on:
  workflow_call:
    inputs:
      name:
        description: Enter name
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: greeting step
        run: echo "Hi, ${{ inputs.name }}, welcome to  reusable workflows"