name: Hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: |
          echo "line one"
          echo "line two"
          echo "line three"