name: deploy to s3
on: push
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::030959774675:role/githubactions-s3-access
          aws-region: us-east-1

      - name: verify aws identity
        run: aws sts get-caller-identity

      - name: deploy idex.html to s3 bucket
        run: aws s3 cp index.html s3://practice-s3-030959774675-us-east-1-an/index.html